name: Deploy to Azure App Service

on:
  workflow_run:
    workflows: ["Build & Push Docker Image"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy Docker Image to Azure Web App
        run: |
          az webapp config container set \
            --name portal-kharis99 \
            --resource-group rg-kharisediwardana \
            --docker-custom-image-name kewtz9/my-js-app:latest \
            --docker-registry-server-url https://index.docker.io
